//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1117.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public string cod_cita { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> valor { get; set; }
        public string diagnostico { get; set; }
        public string nom_acompañante { get; set; }
        public string id_paciente1 { get; set; }
        public string id_medico1 { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
